Repository TokisanGames/Terrain3D, pull requests merged in 2024-12, with the labels that each got.

#564 force decompress textures when building arrays in compatibility
  doc/docs/platforms.md
  src/terrain_3d_assets.cpp
Labels: enhancement

#567 Provide raymarching mode to get_intersection
  doc/api/class_terrain3d.rst
  doc/classes/Terrain3D.xml
  project/addons/terrain_3d/editor.gd
  src/terrain_3d.cpp
  src/terrain_3d.h
Labels: bug

#568 Use Cmd instead of Ctrl on macOS
  doc/docs/tutorial_videos.md
  doc/docs/user_interface.md
  project/addons/terrain_3d/editor.gd
Labels: bug, usability

#578 Fix gamma causing nans
  src/terrain_3d_editor.cpp
Labels: bug

#510 Embed XML API documentation into the engine
  SConstruct
  Terrain3D.vcxproj
  Terrain3D.vcxproj.filters
  doc/api/class_terrain3d.rst
  doc/api/class_terrain3dassets.rst
  doc/api/class_terrain3ddata.rst
  doc/api/class_terrain3deditor.rst
  doc/api/class_terrain3dinstancer.rst
  doc/api/class_terrain3dmaterial.rst
  doc/api/class_terrain3dmeshasset.rst
  doc/api/class_terrain3dregion.rst
  doc/api/class_terrain3dtextureasset.rst
  doc/api/class_terrain3dutil.rst
  doc/api/index.rst
  doc/build_docs.sh
  doc/doc_classes/Terrain3D.xml
  doc/doc_classes/Terrain3DAssets.xml
  doc/doc_classes/Terrain3DData.xml
  doc/doc_classes/Terrain3DEditor.xml
  doc/doc_classes/Terrain3DInstancer.xml
  doc/doc_classes/Terrain3DMaterial.xml
  doc/doc_classes/Terrain3DMeshAsset.xml
  doc/doc_classes/Terrain3DRegion.xml
  doc/doc_classes/Terrain3DTextureAsset.xml
  doc/doc_classes/Terrain3DUtil.xml
Labels: documentation, enhancement

#581 Reorganize editor plugin files
  CONTRIBUTING.md
  project/addons/terrain_3d/extras/import_sgt.gd
  project/addons/terrain_3d/extras/minimum.gdshader
  project/addons/terrain_3d/extras/project_on_terrain3d.gd
  project/addons/terrain_3d/menu/bake_lod_dialog.gd
  project/addons/terrain_3d/menu/bake_lod_dialog.tscn
  project/addons/terrain_3d/menu/baker.gd
  project/addons/terrain_3d/menu/channel_packer.gd
  project/addons/terrain_3d/menu/channel_packer.tscn
  project/addons/terrain_3d/menu/channel_packer_dragdrop.gd
  project/addons/terrain_3d/menu/channel_packer_import_template.txt
  project/addons/terrain_3d/menu/directory_setup.gd
  project/addons/terrain_3d/menu/directory_setup.tscn
  project/addons/terrain_3d/menu/terrain_menu.gd
  project/addons/terrain_3d/plugin.cfg
  project/addons/terrain_3d/src/asset_dock.gd
  project/addons/terrain_3d/src/double_slider.gd
  project/addons/terrain_3d/src/editor_plugin.gd
  project/addons/terrain_3d/src/gradient_operation_builder.gd
  project/addons/terrain_3d/src/multi_picker.gd
  project/addons/terrain_3d/src/operation_builder.gd
  project/addons/terrain_3d/src/region_gizmo.gd
  project/addons/terrain_3d/src/tool_settings.gd
  project/addons/terrain_3d/src/toolbar.gd
  project/addons/terrain_3d/src/ui.gd
  project/addons/terrain_3d/tools/importer.gd
  project/addons/terrain_3d/utils/terrain_3d_objects.gd
  project/addons/terrain_3d/utils/transform_changed_notifier.gd
  project/demo/data/assets.tres
Labels: building

#582 Expose debug views from Terrain3D node
  doc/api/class_terrain3d.rst
  doc/doc_classes/Terrain3D.xml
  src/terrain_3d.cpp
  src/terrain_3d.h
  src/terrain_3d_material.cpp
  src/terrain_3d_material.h
Labels: usability
