Repository TokisanGames/Terrain3D, pull requests merged in 2025-06, with the labels that each got.

#730 Fix #729 - Touch screen inverted setting
  project/addons/terrain_3d/src/editor_plugin.gd
  project/addons/terrain_3d/src/tool_settings.gd
  project/addons/terrain_3d/src/toolbar.gd
  project/addons/terrain_3d/src/ui.gd
Labels: 1.0.1

#733 Region undo bugs
  src/terrain_3d_data.cpp
  src/terrain_3d_data.h
  src/terrain_3d_editor.cpp
  src/terrain_3d_editor.h
  src/terrain_3d_instancer.cpp
  src/terrain_3d_instancer.h
  src/terrain_3d_util.cpp
  src/terrain_3d_util.h
Labels: 1.0.1

#744 Add debug heightmap min and max values
  Terrain3D.vcxproj
  Terrain3D.vcxproj.filters
  src/shaders/debug_views.glsl
  src/shaders/overlays.glsl
  src/terrain_3d_material.cpp
Labels: enhancement

#732 Add instance on all collision
  Terrain3D.vcxproj.filters
  project/addons/terrain_3d/src/tool_settings.gd
  project/addons/terrain_3d/src/ui.gd
  src/terrain_3d.cpp
  src/terrain_3d.h
  src/terrain_3d_editor.h
  src/terrain_3d_instancer.cpp
  src/terrain_3d_instancer.h
Labels: enhancement, important
