Repository TokisanGames/Terrain3D, pull requests merged in 2025-02, with the labels that each got.

#613 Size DoubleSlider based on display scale
  project/addons/terrain_3d/src/double_slider.gd
  project/addons/terrain_3d/src/tool_settings.gd
Labels: bug, usability

#620 Fix region data reading for linux dedicated server export
  src/terrain_3d_data.cpp
Labels: bug

#627 Expose physics material
  doc/api/class_terrain3d.rst
  doc/api/class_terrain3dcollision.rst
  doc/doc_classes/Terrain3D.xml
  doc/doc_classes/Terrain3DCollision.xml
  doc/docs/collision.md
  doc/docs/programming_languages.md
  src/terrain_3d.cpp
  src/terrain_3d.h
  src/terrain_3d_collision.cpp
  src/terrain_3d_collision.h
Labels: enhancement, api
